[character]
success_symbol = "â¯"
error_symbol = "âœ—"
vicmd_symbol = "â®"

[directory]
style = "bold cyan"

[git_branch]
symbol = "î‚  "
style = "bold purple"

[git_status]
style = "yellow"
format = '([\[$all_status$ahead_behind\]]($style))'

[python]
symbol = "ğŸ "
style = "bold green"
format = 'via [$symbol$version]($style) '

[cmd_duration]
min_time = 500
format = "took [$duration]($style) "

[battery]
disabled = true
full_symbol = "ğŸ”‹"
charging_symbol = "âš¡"
discharging_symbol = "ğŸ’€"

